baseURL: https://uh-zz.github.io/

languageCode: jp
title: 'small land'
theme: 'toha'

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  description: 技術とポエムを垂れ流しています
  images:
    - images/bio_1.jpg

  background: 'images/background-min.jpg'
  logo:
    main: images/bio.jpg
    inverted: images/bio.jpg
    favicon: images/bio.jpg

  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/uh-zz/small-land
  gitBranch: main

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration.
  # This feature has been implemented for Mailchimp only for now.
  # You can also hide it from the footer.
  newsletter:
    # specify whether you want to display the newsletter form
    enable: false

social:
  twitter: _uhzz_
